version: "3.7"

services:
  configserver:
    image:  nl.bentels.confserv.test/configserver:0.0.1-SNAPSHOT
    ports:
    - "8088:8088"
    networks:
    - backend
    hostname: configserver
    environment:
    - SPRING_CLOUD_CONFIG_SERVER_VAULT_HOST=vault
    
  service:
    image: nl.bentels.confserv.test/service:0.0.1-SNAPSHOT
    ports:
    - "8080:8080"
    networks:
    - backend
    environment:
    - SPRING_CONFIG_IMPORT=configserver:http://configserver:8088/
    - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_RETRY_SUPPORT=debug
    depends_on: 
    - configserver
    
networks:
  backend:
    external: true
    name: config-server-test_backend
