version: "3.7"

services:
  configserver:
    image:  nl.bentels.confserv.test/configserver:0.0.1-SNAPSHOT
    networks:
    - backend
    hostname: configserver
    environment:
    - SPRING_CLOUD_CONFIG_SERVER_VAULT_HOST=vault
    - LOGGING_LEVEL_ROOT=warn
    
  serviceregistry:
    image:  nl.bentels.confserv.test/serviceregistry:0.0.1-SNAPSHOT
    networks:
    - backend
    hostname: serviceregistry
    depends_on: 
    - configserver
    environment:
    - LOGGING_LEVEL_ROOT=info
    
  service_0:
    image: nl.bentels.confserv.test/service:0.0.1-SNAPSHOT
    networks:
    - backend
    depends_on: 
    - configserver
    - serviceregistry

  service_1:
    image: nl.bentels.confserv.test/service:0.0.1-SNAPSHOT
    networks:
    - backend
    depends_on: 
    - configserver
    - serviceregistry
    
  gateway:
    image: nl.bentels.confserv.test/gateway:0.0.1-SNAPSHOT
    ports:
    - "80:8080"
    networks:
    - backend
    hostname: gateway
    depends_on:
    - serviceregistry
    environment:
    - LOGGING_LEVEL_ROOT=warn
     
    
networks:
  backend:
    external: true
    name: config-server-test_backend
