spring:
  application:
    name: test-app
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        multiplier: 1.1
        initial-interval: 4000
        max-interval: 10000
  config:
    import: optional:configserver:http://configserver:8088/
#    - configserver:http://localhost:8088/?fail-fast=true&max-attempts=100&max-interval=15000&multiplier=1.2&initial-interval=1100
  profiles:
    active:
    - default
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
logging:
  level:
    root: info