spring:
  application:
    name: test-app
  config:
    import: 
    - configserver:http://localhost:8088/
  profiles:
    active:
    - default
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include:
        - "*"
logging:
  level:
    root: info