spring:
  application:
    name: booking-app
  cloud:
    config:
      fail-fast: true
      retry:
        max-attempts: 10
        multiplier: 1.1
        initial-interval: 4000
        max-interval: 10000
  config:
    import: optional:configserver:http://configserver:8088/
